name: deploy to hostinger
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # with:
        #   sparse-checkout: |
        #     dist
      - name: Create Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - name: Install Packages and Build Application
        run: | #npm install
          npm install -g @vue/cli
          npm run build
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: develop
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
