name: Deployable Application Build
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install Packages and Build Application
        run: | 
          npm install
          npm run build
      
      - name: Checkout production branch and Fetch lastest changes
        run: |
          git fetch origin production
          git checkout production
          git pull origin production --rebase

      - name: Deploy
        uses: s0/git-publish-subdir-action@production
        env:
          REPO: self
          BRANCH: production
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
