name: Deployable Application Build
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          # cache: "npm"
          
      - name: Install Packages and Build Application
        working-directory: client
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: production
          FOLDER: client/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
